# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: BUILD
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...

    - name: TESTS
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //... --test_output=all --nocache_test_results

    - name: Junit Report to Annotations
      uses: ashley-taylor/junit-report-annotations-action@v1.0
      if: always()
      with:
        # github token
        access-token: ${{ secrets.GITHUB_TOKEN }}
        # glob to junit xml files
        path: bazel-testlogs/AllTests/*.xml
        # include summary annotation
        includeSummary: true
        # max number of failed tests to include
        numFailures: 10
        # path to test source
        testSrcPath: src/test/java
